"""empty message

Revision ID: 3a37952a9b0b
Revises: 78b3d24ec5dc
Create Date: 2019-07-08 18:27:42.719468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a37952a9b0b'
down_revision = '78b3d24ec5dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_deploy_strategy', sa.Column('name', sa.String(length=32), nullable=True))
    op.add_column('cluster_inspect_info', sa.Column('cpu_lim_avg', sa.Numeric(precision=12, scale=6), nullable=True))
    op.add_column('cluster_inspect_info', sa.Column('cpu_req_avg', sa.Numeric(precision=12, scale=6), nullable=True))
    op.add_column('cluster_inspect_info', sa.Column('cpu_usage_avg', sa.Numeric(precision=12, scale=6), nullable=True))
    op.add_column('cluster_inspect_info', sa.Column('mem_lim_avg', sa.Numeric(precision=12, scale=6), nullable=True))
    op.add_column('cluster_inspect_info', sa.Column('mem_usage_avg', sa.Numeric(precision=12, scale=6), nullable=True))
    op.add_column('cluster_inspect_info', sa.Column('pod_num', sa.Integer(), nullable=True))
    op.drop_column('cluster_inspect_info', 'pods_num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_inspect_info', sa.Column('pods_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('cluster_inspect_info', 'pod_num')
    op.drop_column('cluster_inspect_info', 'mem_usage_avg')
    op.drop_column('cluster_inspect_info', 'mem_lim_avg')
    op.drop_column('cluster_inspect_info', 'cpu_usage_avg')
    op.drop_column('cluster_inspect_info', 'cpu_req_avg')
    op.drop_column('cluster_inspect_info', 'cpu_lim_avg')
    op.drop_column('cluster_deploy_strategy', 'name')
    # ### end Alembic commands ###
