"""empty message

Revision ID: 5215aa1534a8
Revises: 648f3f649c79
Create Date: 2019-06-16 23:07:39.450817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5215aa1534a8'
down_revision = '648f3f649c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('client', 'expires_at')
    op.drop_column('oauth2_client', 'expires_at')
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.add_column('oauth2_client', sa.Column('expires_at', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('client', sa.Column('expires_at', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('child')
    op.drop_table('parent')
    # ### end Alembic commands ###
