"""empty message

Revision ID: 766ff28e4900
Revises: eb02a7e9c7e4
Create Date: 2019-07-15 08:33:22.347544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766ff28e4900'
down_revision = 'eb02a7e9c7e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_product_config',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=32), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['cluster_deploy_strategy.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_name')
    )
    op.add_column('cluster_inspect_info', sa.Column('mem_req_avg', sa.Numeric(precision=12, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster_inspect_info', 'mem_req_avg')
    op.drop_table('strategy_product_config')
    # ### end Alembic commands ###
