"""empty message

Revision ID: 82d6c20c6f6f
Revises: aa068091fd43
Create Date: 2019-12-28 08:34:14.300510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d6c20c6f6f'
down_revision = 'aa068091fd43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('object_uuid', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('object_table', sa.String(length=100), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('utime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=True),
    sa.Column('field', sa.String(length=32), nullable=True),
    sa.Column('before', sa.PickleType(), nullable=True),
    sa.Column('after', sa.PickleType(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_record')
    op.drop_table('transaction')
    # ### end Alembic commands ###
