"""empty message

Revision ID: aa068091fd43
Revises: b540fb6f36b4
Create Date: 2019-12-27 16:54:14.521186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa068091fd43'
down_revision = 'b540fb6f36b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
