"""empty message

Revision ID: eb02a7e9c7e4
Revises: 6fa3e19f888d
Create Date: 2019-07-12 14:38:24.847197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb02a7e9c7e4'
down_revision = '6fa3e19f888d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expression',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('infix', sa.String(length=255), nullable=True),
    sa.Column('relation_operator', sa.String(length=64), nullable=True),
    sa.Column('operator_value', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['cluster_deploy_strategy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cluster_inspect_info', sa.Column('cluster_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cluster_inspect_info', 'cluster', ['cluster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cluster_inspect_info', type_='foreignkey')
    op.drop_column('cluster_inspect_info', 'cluster_id')
    op.drop_table('expression')
    # ### end Alembic commands ###
